"""Central configuration for the Semantic Scale Network application."""

from pathlib import Path
import os

PROJECT_ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = PROJECT_ROOT / "data"
INTERIM_DIR = DATA_DIR / "interim"
PROCESSED_DIR = DATA_DIR / "processed"
MODELS_DIR = DATA_DIR / "models"
DOCS_DIR = DATA_DIR / "docs"

SSN_DIR = PROJECT_ROOT / "ssn"
DB_PATH = SSN_DIR / "db" / "ssn.sqlite"

# Normalized CSV used for import (generated by scripts/normalize_construct_reported.py from items_master_ipip.csv)
IPIP_MASTER_CSV = INTERIM_DIR / "items_master_ipip_normalized.csv"
IPIP_EMBEDDINGS_NPY = PROCESSED_DIR / "embeddings_person_ipip.npy"
IPIP_ITEM_IDS_CSV = PROCESSED_DIR / "item_ids_ipip.csv"
FAISS_INDEX_PATH = PROCESSED_DIR / "ssn_faiss.index"

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "")
EMBEDDING_MODEL = "text-embedding-3-small"
EMBEDDING_DIM = 768
LLM_MODEL = "gpt-4o"

DEFAULT_TOP_N = 5
MAX_TOP_N = 15

SIMILARITY_THRESHOLDS = {
    "high": 0.85,
    "medium": 0.65,
}

STREAMLIT_PAGE_ICON = "🔬"
STREAMLIT_TITLE = "Semantic Scale Network"
